# Generated by Django 5.2 on 2025-04-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatMessage',
            new_name='Message',
        ),
    ]
